const backButtonIcon = "assets/images/vectors/back_button.svg";
const facebookIcon = "assets/images/vectors/facebook.svg";
const googleIcons = "assets/images/vectors/google.svg";
const background = "assets/images/decoration/background.png"; //Delete this asset and change SvgPicture to NetworkImage
const searchIcon = "assets/images/vectors/search.svg";
const filterIcon = "assets/images/vectors/filter.svg";
const menuDecoration = "assets/images/decoration/menu.jpg"; //Delete this asset and change SvgPicture to NetworkImage
const talkLetters = 'assets/images/decoration/talk_letters.png';
const menuIcon = 'assets/images/vectors/menu.svg';
const calendarIcon = 'assets/images/vectors/calendar.svg';
const starIcon = 'assets/images/vectors/star.svg';
const userIcon = 'assets/images/vectors/user.svg';
const arrowTitle = 'assets/images/decoration/arrow_title.png';
const coffeImage = 'assets/images/decoration/coffeImage.png';